### ISSUE TITLE
Create a Paper Prototype

### ISSUE THREAD

**Issue by scott-stockwell** [codeforkansascity/KS-CMR#4]
**Goal**: Create a prototype of the form used to gather information from users to access their eligibility for expungement. 

**Key Resources**:
- Current [Miro board](https://miro.com/app/board/o9J_lghg32w=/) where the prototype is being built
- Previous [Miro board](https://miro.com/app/board/o9J_l2gNnC8=/) used to collect information about expungement

**Comment by wdcrumpler-kcdd** [comment]
**Current Status**:
- Version 0.1 of form drafted at current Miro board linked above

**To Do**
- [ ] Draft introductory text for landing page
- [ ] Draft text for About page
- [ ] Complete FAQ answers
- [ ] Review first screen questionnaire
- [ ] Review second screen questionnaire
- [ ] Draft text for screen failure page
- [ ] Collect list of personal information needed to submit expungement request, municipal appeal, and expungement of arrest record
